# Generated by Django 4.2 on 2025-02-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_companydetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
